"""create events table

Revision ID: a02bd8a1ea39
Revises: 
Create Date: 2026-02-19 21:39:34.266090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02bd8a1ea39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_source', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('app_name', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_app_name', ['app_name'], unique=False)
        batch_op.create_index('ix_events_event_type', ['event_type'], unique=False)
        batch_op.create_index('ix_events_session_id', ['session_id'], unique=False)
        batch_op.create_index('ix_events_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_timestamp')
        batch_op.drop_index('ix_events_session_id')
        batch_op.drop_index('ix_events_event_type')
        batch_op.drop_index('ix_events_app_name')

    op.drop_table('events')
    # ### end Alembic commands ###
