name: Build and Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  actions: read

jobs:
  pack-and-publish:
    uses: ./.github/workflows/pack-and-publish.yaml
    with:
      charm_name: marketplace-analytics
      channel: latest/edge
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
